// Generated by CoffeeScript 1.7.1
(function() {
  define(["jquery"], function($) {
    var i, iStr, images;
    images = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 176; i = _i += 5) {
        iStr = "" + i;
        iStr = ((function() {
          var _j, _ref, _results1;
          _results1 = [];
          for (_j = _ref = iStr.length; _ref <= 4 ? _j <= 4 : _j >= 4; _ref <= 4 ? _j++ : _j--) {
            _results1.push("0");
          }
          return _results1;
        })()).join() + iStr;
        _results.push("images/" + iStr + ".png");
      }
      return _results;
    })();
    return $(function() {
      var $container;
      $container = $("#container");
      return $container.rotator({
        width: 300,
        height: 200,
        images: images
      });
    });
  });

}).call(this);
